spring.application.name=MicroSaaS
# 1. Database Connection Settings
#spring.datasource.url=jdbc:mysql://localhost:3306/stackly1
#spring.datasource.username=root
#spring.datasource.password=Harish@1325
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=${PORT:8080}

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://ep-solitary-darkness-aogk6gdk-pooler.c-2.ap-southeast-1.aws.neon.tech/microSaas
spring.datasource.username=neondb_owner
spring.datasource.password=npg_XpLosT1kM2Eb
spring.datasource.driver-class-name=org.postgresql.Driver


# 2. Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



#Email Verification purpose
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_USERNAME}
spring.mail.password=${BREVO_PASSWORD}

BREVO_API_KEY=${BREVO_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000



# Redis
spring.data.redis.url=${REDIS_URL}


# Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_SCOPE}

# Microsoft
spring.security.oauth2.client.registration.microsoft.provider=${MICROSOFT_PROVIDER}
spring.security.oauth2.client.registration.microsoft.client-id=${MICROSOFT_CLIENT_ID}
spring.security.oauth2.client.registration.microsoft.client-secret=${MICROSOFT_CLIENT_SECRET}
spring.security.oauth2.client.registration.microsoft.scope=${MICROSOFT_SCOPE}
spring.security.oauth2.client.registration.microsoft.redirect-uri=${MICROSOFT_REDIRECT_URI}
spring.security.oauth2.client.registration.microsoft.authorization-grant-type=${MICROSOFT_AUTH_GRANT_TYPE}
spring.security.oauth2.client.registration.microsoft.client-authentication-method=${MICROSOFT_CLIENT_AUTH_METHOD}
spring.security.oauth2.client.registration.microsoft.client-name=${MICROSOFT_CLIENT_NAME}

spring.security.oauth2.client.provider.microsoft.issuer-uri=${MICROSOFT_ISSUER_URI}

# Slack
spring.security.oauth2.client.registration.slack.client-id=${SLACK_CLIENT_ID}
spring.security.oauth2.client.registration.slack.client-secret=${SLACK_CLIENT_SECRET}
spring.security.oauth2.client.registration.slack.scope=${SLACK_SCOPE}
spring.security.oauth2.client.registration.slack.client-name=${SLACK_CLIENT_NAME}
spring.security.oauth2.client.registration.slack.authorization-grant-type=${SLACK_AUTH_GRANT_TYPE}
spring.security.oauth2.client.registration.slack.redirect-uri=${SLACK_REDIRECT_URI}

spring.security.oauth2.client.provider.slack.authorization-uri=${SLACK_AUTH_URI}
spring.security.oauth2.client.provider.slack.token-uri=${SLACK_TOKEN_URI}
spring.security.oauth2.client.provider.slack.user-info-uri=${SLACK_USER_INFO_URI}
spring.security.oauth2.client.provider.slack.jwk-set-uri=${SLACK_JWK_SET_URI}
spring.security.oauth2.client.provider.slack.user-name-attribute=${SLACK_USER_NAME_ATTRIBUTE}